import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes } from 'node:crypto';
import sql from 'mssql';
import {hashPassword,verifyPassword,encrypt,decrypt,identifier,validateSQL,buildQuery} from './security.mjs';
try{process.loadEnvFile()}catch{}
const root=path.resolve(import.meta.dirname,'..'),dataDir=process.env.DATA_DIR||path.join(root,'data');fs.mkdirSync(dataDir,{recursive:true});
if(!/^[a-f0-9]{64}$/i.test(process.env.ENCRYPTION_KEY||''))throw Error('请在 .env 中配置 64 位十六进制 ENCRYPTION_KEY');
const key=Buffer.from(process.env.ENCRYPTION_KEY,'hex'),db=new DatabaseSync(path.join(dataDir,'platform.sqlite'));
db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS items(type TEXT,id TEXT,body TEXT,PRIMARY KEY(type,id)); CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,userId TEXT,accountId TEXT,expires INTEGER); CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,at TEXT,userId TEXT,username TEXT,accountId TEXT,reportId TEXT,reportName TEXT,action TEXT,success INTEGER,rows INTEGER,duration INTEGER,detail TEXT);`);
const all=t=>db.prepare('SELECT body FROM items WHERE type=?').all(t).map(x=>JSON.parse(x.body));
const get=(t,id)=>{const r=db.prepare('SELECT body FROM items WHERE type=? AND id=?').get(t,id);return r?JSON.parse(r.body):null};
const save=(t,o)=>db.prepare('INSERT OR REPLACE INTO items VALUES(?,?,?)').run(t,o.id,JSON.stringify(o));
if(!all('users').length){save('roles',{id:'admin',name:'系统管理员',admin:true,permissions:{}});save('accounts',{id:'default',name:'默认账套',orgId:'1',enabled:true});save('users',{id:'admin',username:'admin',name:'系统管理员',password:hashPassword(process.env.ADMIN_PASSWORD),roleIds:['admin'],accountIds:['default'],enabled:true})}
const clean=(t,o)=>{const v={...o};delete v.password;delete v.secret;return v};
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
const audit=(u,a,r,action,success,rows=0,duration=0,detail='')=>db.prepare('INSERT INTO audit(at,userId,username,accountId,reportId,reportName,action,success,rows,duration,detail) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(new Date().toISOString(),u.id,u.username,a?.id||'',r?.id||'',r?.name||'',action,success?1:0,rows,duration,detail);
const roles=u=>u.roleIds.map(id=>get('roles',id)).filter(Boolean);const admin=u=>roles(u).some(r=>r.admin);const allowed=(u,id,action)=>admin(u)||roles(u).some(r=>r.permissions?.[id]?.includes(action));
const attempts=new Map();
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>1024*1024)throw fail('请求过大',413)}try{return s?JSON.parse(s):{}}catch{throw fail('请求格式错误')}}
async function connect(d){return new sql.ConnectionPool({server:d.host,port:Number(d.port||1433),database:d.database,user:d.username,password:decrypt(d.secret,key),connectionTimeout:10000,requestTimeout:30000,pool:{max:2,min:0,idleTimeoutMillis:1000},options:{encrypt:true,trustServerCertificate:!!d.trustCertificate,readOnlyIntent:true}}).connect()}
function validate(t,b,old){const o={...b,id:old?.id||randomBytes(8).toString('hex')};if(!o.name?.trim())throw fail('名称不能为空');if(t==='users'){if(!/^[\w.@-]{2,80}$/.test(o.username||''))throw fail('登录名格式错误');if(all(t).some(x=>x.username===o.username&&x.id!==o.id))throw fail('登录名已存在');o.password=b.password?hashPassword(b.password):old?.password;if(!o.password)throw fail('请设置初始密码');if(!Array.isArray(o.roleIds)||!o.roleIds.every(x=>get('roles',x))||!Array.isArray(o.accountIds)||!o.accountIds.every(x=>get('accounts',x)))throw fail('角色或账套无效');o.enabled=!!o.enabled;if(old&&admin(old)&&(!o.enabled||!admin(o))&&!all('users').some(x=>x.id!==o.id&&x.enabled&&admin(x)))throw fail('必须保留一个启用的管理员')}
if(t==='connections'){if(!o.host||!o.database||!o.username)throw fail('请填写服务器、数据库和账号');o.secret=b.password?encrypt(b.password,key):old?.secret;delete o.password;if(!o.secret)throw fail('请填写数据库密码')}
if(t==='accounts'){if(o.orgId===undefined||String(o.orgId).trim()==='')throw fail('组织 ID 不能为空');o.orgId=String(o.orgId);o.enabled=!!o.enabled}
if(t==='roles'){if(old?.admin&&!o.admin)throw fail('内置管理员角色不可降级');o.admin=old?.admin||false;o.permissions=o.permissions||{}}
if(t==='reports'){validateSQL(o.sql);identifier(o.orgColumn);if(!get('connections',o.connectionId))throw fail('请选择数据源');if(!Array.isArray(o.fields)||!o.fields.length||o.fields.length>100)throw fail('请配置 1–100 个字段');const keys=new Set();for(const f of o.fields){identifier(f.key);if(keys.has(f.key)||!f.label)throw fail('字段重复或名称为空');keys.add(f.key)}o.enabled=!!o.enabled}
return o}
const server=http.createServer(async(req,res)=>{const send=(v,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(v))};try{const url=new URL(req.url,'http://localhost'),p=url.pathname;res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; style-src 'self'; script-src 'self'; frame-ancestors 'none'");if(!p.startsWith('/api/')){if(req.method!=='GET')throw fail('不支持的请求',405);const file={'/':'index.html','/app.js':'app.js','/style.css':'style.css','/favicon.svg':'favicon.svg'}[p];if(!file)throw fail('页面不存在',404);res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'text/javascript; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':'image/svg+xml');res.end(fs.readFileSync(path.join(root,'dist',file)));return}
if(!['GET','HEAD'].includes(req.method)&&req.headers['x-requested-with']!=='ReportPlatform')throw fail('请求校验失败',403);
if(p==='/api/login'&&req.method==='POST'){const b=await body(req),ip=req.socket.remoteAddress,bucket=attempts.get(ip)||{n:0,until:Date.now()+900000};if(bucket.until<Date.now()){bucket.n=0;bucket.until=Date.now()+900000}if(bucket.n>=10)throw fail('登录尝试过多，请 15 分钟后重试',429);const u=all('users').find(x=>x.username===b.username);if(!u?.enabled||!verifyPassword(String(b.password||''),u.password)){bucket.n++;attempts.set(ip,bucket);throw fail('账号或密码错误',401)}const accounts=u.accountIds.map(x=>get('accounts',x)).filter(x=>x?.enabled);if(!b.accountId){send({accounts:accounts.map(x=>({id:x.id,name:x.name}))});return}const a=accounts.find(x=>x.id===b.accountId);if(!a)throw fail('无权登录该账套',403);attempts.delete(ip);db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(token,u.id,a.id,Date.now()+8*3600000);res.setHeader('Set-Cookie',`session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${process.env.COOKIE_SECURE==='true'?'; Secure':''}`);audit(u,a,null,'login',true);send({ok:true});return}
const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('session='))?.slice(8),session=token&&db.prepare('SELECT * FROM sessions WHERE token=? AND expires>?').get(token,Date.now()),u=session&&get('users',session.userId),a=session&&get('accounts',session.accountId);if(!u?.enabled||!a?.enabled||!u.accountIds.includes(a.id))throw fail('请重新登录',401);
if(p==='/api/logout'&&req.method==='POST'){db.prepare('DELETE FROM sessions WHERE token=?').run(token);res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');send({ok:true});return}
if(p==='/api/bootstrap'){send({user:clean('users',u),account:a,admin:admin(u),reports:all('reports').filter(r=>r.enabled&&allowed(u,r.id,'view')).map(r=>({id:r.id,name:r.name,description:r.description,category:r.category,fields:r.fields,actions:['view','query','export','edit'].filter(x=>allowed(u,r.id,x))}))});return}
const match=p.match(/^\/api\/reports\/([^/]+)\/(query|export)$/);if(match&&req.method==='POST'){const r=get('reports',match[1]),action=match[2];if(!r?.enabled||!allowed(u,r.id,'view')||!allowed(u,r.id,action))throw fail('没有该报表的操作权限',403);const start=Date.now();let pool;try{const b=await body(req),q=buildQuery(r,a.orgId,b.filters,action==='export'?10001:501),d=get('connections',r.connectionId);if(!d)throw fail('数据源不存在');pool=await connect(d);const request=pool.request();for(const x of q.params)request.input(x.name,sql.NVarChar(4000),x.value);const result=await request.query(q.sql),cap=action==='export'?10000:500,truncated=result.recordset.length>cap,rows=result.recordset.slice(0,cap);if(action==='export'&&truncated)throw fail('导出超过 10000 行，请缩小筛选范围');audit(u,a,r,action,true,rows.length,Date.now()-start);if(action==='query'){send({rows,truncated,limit:cap,duration:Date.now()-start});return}const escape=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const csv='\ufeff'+[r.fields.map(f=>escape(f.label)).join(','),...rows.map(row=>r.fields.map(f=>escape(row[f.key])).join(','))].join('\r\n');res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(r.name+'.csv'),'Cache-Control':'no-store'});res.end(csv);return}catch(e){audit(u,a,r,action,false,0,Date.now()-start,e.status?e.message:'数据库查询失败');throw fail(e.status?e.message:'数据库连接或查询失败，请管理员核对数据源与 SQL',e.status||400)}finally{await pool?.close()}}
if(p==='/api/audit'&&admin(u)){const day=url.searchParams.get('date')||new Date(Date.now()+8*3600000).toISOString().slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(day))throw fail('日期无效');const records=db.prepare("SELECT * FROM audit WHERE date(at,'+8 hours')=? ORDER BY id DESC LIMIT 1000").all(day);const summary=db.prepare("SELECT username,reportName,accountId,SUM(action='query') queries,SUM(action='export') exports,SUM(success=0) failures FROM audit WHERE date(at,'+8 hours')=? AND action IN ('query','export') GROUP BY userId,username,reportId,reportName,accountId").all(day);send({records,summary});return}
const m=p.match(/^\/api\/admin\/(users|roles|accounts|connections|reports)(?:\/([^/]+))?(?:\/(test))?$/);if(m){const [,t,id,test]=m,old=id?get(t,id):null;const editor=t==='reports'&&id&&allowed(u,id,'edit');if(!admin(u)&&!editor)throw fail('没有管理权限',403);if(test&&req.method==='POST'&&t==='connections'){let pool;try{pool=await connect(old);await pool.request().query('SELECT 1 AS ok');send({ok:true,message:'连接成功'})}catch{throw fail('连接失败，请检查地址、账号和证书配置')}finally{await pool?.close()}return}if(req.method==='GET'){send(id?clean(t,old):all(t).map(x=>clean(t,x)));return}if(['POST','PUT'].includes(req.method)){if(req.method==='PUT'&&!old)throw fail('记录不存在',404);const o=validate(t,await body(req),old);save(t,o);if(t==='users')db.prepare('DELETE FROM sessions WHERE userId=?').run(o.id);audit(u,a,t==='reports'?o:null,'save:'+t,true,0,0,o.id);send(clean(t,o));return}if(req.method==='DELETE'){if(!admin(u))throw fail('没有管理权限',403);if(!old)throw fail('记录不存在',404);if(t==='users'&&(id===u.id||admin(old)))throw fail('不能删除当前用户或管理员');if(t==='roles'&&(old.admin||all('users').some(x=>x.roleIds.includes(id))))throw fail('角色正在使用，无法删除');if(t==='accounts'&&all('users').some(x=>x.accountIds.includes(id)))throw fail('账套正在使用，无法删除');if(t==='connections'&&all('reports').some(x=>x.connectionId===id))throw fail('数据源正在使用，无法删除');db.prepare('DELETE FROM items WHERE type=? AND id=?').run(t,id);audit(u,a,null,'delete:'+t,true,0,0,id);send({ok:true});return}}
throw fail('接口不存在',404)}catch(e){if(!res.headersSent)send({error:e.status?e.message:'操作失败：'+(e.message.includes('密码')||e.message.includes('字段')||e.message.includes('SELECT')?e.message:'请检查配置')},e.status||400);else res.end()}});
server.listen(Number(process.env.PORT||3080),process.env.HOST||'127.0.0.1',()=>console.log('报表平台已启动 http://'+(process.env.HOST||'127.0.0.1')+':'+(process.env.PORT||3080)));
