using System.Security.Cryptography;
using System.Text.Json;
using ReportPlatform.Infrastructure;
using ReportPlatform.Models;
using ReportPlatform.Services;
using Xunit;

namespace ReportPlatform.Tests;

public sealed class SecurityTests
{
    [Fact]
    public void QueryReportsMissingOrganizationAndDisplayColumnsClearly()
    {
        var query = new PreparedQuery("", "", "", new Dictionary<string, string>(), "", "1", ["Mocode"]);
        var missingOrg = Assert.Throws<ApiException>(() => ReportColumns.Validate(query, ["MoCode", "TenantId"]));
        Assert.Contains("组织 ID 字段“1”", missingOrg.Message);
        Assert.Contains("不是账套组织 ID 值", missingOrg.Message);
        ReportColumns.Validate(query with { OrgColumn = "TenantId" }, ["MoCode", "TenantId"]);
        var missingField = Assert.Throws<ApiException>(() => ReportColumns.Validate(query with { OrgColumn = "TenantId", Fields = ["不存在的字段"] }, ["MoCode", "TenantId"]));
        Assert.Contains("不存在的字段", missingField.Message);
        Assert.Contains("权限", SqlFailureMessages.ForNumber(229));
        Assert.Contains("ORDER BY", SqlFailureMessages.ForNumber(1033));
    }
    [Fact]
    public void ChineseFieldNamesAndClosingBracketsAreSafelyQuoted()
    {
        var report = new Report { Sql = "SELECT OrgId AS [组织ID], Amount AS [销售 金额] FROM Orders", OrgColumn = "组织ID", Fields = [new("销售 金额", "金额")] };
        var query = SqlQueryBuilder.Build(report, "200", [new("销售 金额", "gte", JsonSerializer.SerializeToElement(100))]);
        Assert.Contains("q.[组织ID] = @org", query.DataSql);
        Assert.Contains("q.[销售 金额] >= @p0", query.DataSql);
        Assert.Equal("[a]]; DROP TABLE T;--]", SqlQueryBuilder.Identifier("a]; DROP TABLE T;--"));
        Assert.Throws<ApiException>(() => SqlQueryBuilder.Identifier(" "));
        Assert.Throws<ApiException>(() => SqlQueryBuilder.Identifier("name\n"));
        Assert.Throws<ApiException>(() => SqlQueryBuilder.Identifier(new string('a', 129)));
    }
    [Fact]
    public void FieldPreviewUsesAsAliasesAsDisplayNames()
    {
        var fields = SqlAliases.ToFields("SELECT TenantId, MoCode AS [工单编号], Qty AS \"数量\" FROM IcsMo",
            ["TenantId", "工单编号", "数量"]);
        Assert.Equal("", fields[0].Label);
        Assert.Equal("工单编号", fields[1].Label);
        Assert.Equal("数量", fields[2].Label);
    }
    [Fact]
    public void PasswordHashesVerifyAndRejectInvalidPasswords()
    {
        var hash = CredentialService.HashPassword("abc12");
        Assert.True(CredentialService.VerifyPassword("abc12", hash));
        Assert.False(CredentialService.VerifyPassword("WrongPassword!", hash));
        Assert.Throws<ApiException>(() => CredentialService.HashPassword("1234"));
    }
    [Fact]
    public void LegacyScryptPasswordRemainsUsable()
    {
        // Independently generated by Node.js crypto.scryptSync using its defaults.
        const string hash = "0123456789abcdef0123456789abcdef:d29d7c8b64227b3414f95c94745238be76c5558fd66318a3b9b8d2d61fb5e1e1a3b0ba64f8a65e7b6efd5d03188fe24c22edea99cd40c1c202ff27a67e034563";
        Assert.True(CredentialService.VerifyPassword("LegacyPassword123!", hash));
        Assert.False(CredentialService.VerifyPassword("WrongPassword", hash));
    }
    [Fact]
    public void ConnectionPasswordsAreAuthenticatedAndCompatibleWithLegacyFormat()
    {
        var credentials = new CredentialService(new("unused", new string('a', 64), "", false));
        var secret = credentials.Encrypt("DatabasePassword");
        Assert.Equal(3, secret.Split(':').Length);
        Assert.Equal("DatabasePassword", credentials.Decrypt(secret));
        Assert.Equal("DatabasePassword", credentials.Decrypt("010101010101010101010101:d987ec86a89502a8f1fa3f92a865ae6f:66f2587e076f91d00490df8564af1c94"));
        var differentKey = new CredentialService(new("unused", new string('b', 64), "", false));
        Assert.ThrowsAny<CryptographicException>(() => differentKey.Decrypt(secret));
    }
    [Theory]
    [InlineData("DELETE FROM Users")]
    [InlineData("SELECT * INTO Copy FROM Users")]
    [InlineData("SELECT 1; DROP TABLE Users")]
    [InlineData("SELECT 1 -- comment")]
    [InlineData("SELECT * FROM OPENROWSET(x)")]
    public void UnsafeSqlIsRejected(string sql) => Assert.Throws<ApiException>(() => SqlQueryBuilder.Validate(sql));

    [Fact]
    public void OrganizationAndFilterValuesCannotBecomeSql()
    {
        var report = new Report { Sql = "SELECT OrgId, Amount FROM Orders", OrgColumn = "OrgId", Fields = [new("Amount", "金额")] };
        var query = SqlQueryBuilder.Build(report, "1' OR 1=1", [new("Amount", "eq", JsonSerializer.SerializeToElement("0' OR 1=1"))]);
        Assert.Contains("[OrgId] = @org", query.DataSql);
        Assert.DoesNotContain("OR 1=1", query.DataSql);
        Assert.Equal("1' OR 1=1", query.Parameters["org"]);
        Assert.Throws<ApiException>(() => SqlQueryBuilder.Build(report, "1", [new("Other", "eq", JsonSerializer.SerializeToElement(1))]));
    }
    [Fact]
    public void EmptyOrganizationColumnQueriesAllOrganizations()
    {
        var report = new Report { Sql = "SELECT TenantId, Amount FROM Orders", OrgColumn = "", Fields = [new("Amount", "金额")] };
        var query = SqlQueryBuilder.Build(report, "200", []);
        Assert.Empty(query.Parameters);
        Assert.DoesNotContain("@org", query.DataSql);
        Assert.DoesNotContain(" WHERE ", query.DataSql);
        ReportColumns.Validate(query, ["TenantId", "Amount"]);
    }
    [Fact]
    public void CsvNeutralizesSpreadsheetFormulas()
    {
        Assert.Equal("\"'  =1+1\"", CsvExport.Cell("  =1+1"));
        Assert.Equal("\"a\"\"b\"", CsvExport.Cell("a\"b"));
    }
}
